version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - clinica_net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - clinica_net
    restart: unless-stopped

  localhost:
    image: rabbitmq:3-management
    hostname: "localhost"
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data_vol:/var/lib/rabbitmq/
      - rabbitmq_log_vol:/var/log/rabbitmq
    networks:
      - clinica_net
    environment:
      - RABBITMQ_DEFAULT_USER = admin
      - RABBITMQ_DEFAULT_PASS = 1234
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
      image: clinica.webapi:latest
      container_name: webapi_container
      build:
        context: .
        dockerfile: Clinica.Main.WebApi\Dockerfile
      environment:
        - RabbitMq__HostName=localhost
      ports:
        - "8080:8080"
        - "8081:8081"
      networks:
        - clinica_net
      depends_on:
        localhost:
            condition: service_healthy
      restart: always

networks:
  clinica_net:

volumes:
  postgres:
  pgadmin:
  rabbitmq_data_vol:
  rabbitmq_log_vol:
